version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf
    command: ["-c", "/etc/nats/nats.conf"]
    networks:
      - ai-network

  # MCP Servers
  mcp-proxmox:
    build: ./mcp-servers/proxmox
    container_name: mcp-proxmox
    environment:
      - NATS_URL=nats://nats:4222
      - MCP_PORT=8001
    depends_on:
      - nats
    networks:
      - ai-network

  mcp-filesystem:
    build: ./mcp-servers/filesystem
    container_name: mcp-filesystem
    environment:
      - NATS_URL=nats://nats:4222
      - MCP_PORT=8002
    volumes:
      - /tmp/shared:/workspace
    depends_on:
      - nats
    networks:
      - ai-network

  mcp-cloud:
    build: ./mcp-servers/cloud
    container_name: mcp-cloud
    environment:
      - NATS_URL=nats://nats:4222
      - MCP_PORT=8003
    depends_on:
      - nats
    networks:
      - ai-network

  # AI Agents
  orchestrator-agent:
    build: ./agents/orchestrator
    container_name: orchestrator-agent
    environment:
      - NATS_URL=nats://nats:4222
      - AGENT_ID=orchestrator-001
    depends_on:
      - nats
      - mcp-proxmox
      - mcp-filesystem
      - mcp-cloud
    networks:
      - ai-network

  specialist-agent:
    build: ./agents/specialist
    container_name: specialist-agent
    environment:
      - NATS_URL=nats://nats:4222
      - AGENT_ID=specialist-001
    depends_on:
      - nats
    networks:
      - ai-network

  monitor-agent:
    build: ./agents/monitor
    container_name: monitor-agent
    environment:
      - NATS_URL=nats://nats:4222
      - AGENT_ID=monitor-001
    depends_on:
      - nats
    networks:
      - ai-network

  # Dashboard
  dashboard:
    build: ./dashboard
    container_name: ai-dashboard
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - ai-network

  error-aggregator:
    build:
      context: . # Assuming shared is at the same level as error-aggregator
      dockerfile: ./error-aggregator/Dockerfile
    container_name: error-aggregator
    ports:
      - "8081:8081" # Expose the HTTP port
    environment:
      - NATS_URL=nats://nats:4222
      - MAX_ERRORS_STORED=200 # Example: store 200 errors
      - HTTP_PORT=8081 # Ensure this matches the EXPOSE in Dockerfile and app
      - PYTHONUNBUFFERED=1 # Good for seeing logs immediately
    networks:
      - ai-network
    depends_on:
      - nats # Ensures NATS is up before this service starts

networks:
  ai-network:
    driver: bridge
